### ISSUE TITLE
Turn the TerminalDevice into an actual Device.

### ISSUE THREAD

**Issue by chronium** [TheKernelCorp/NuummiteOS#15]
At the moment, TerminalDevice doesn't actually inherit from Device, so the name is a lie. When I attempted myself, for some reason the write and writeln macros did not work. After thorough investigation, couldn't find the cause.

If someone could look into it, great. :D

**Comment by SplittyDev** [comment]
The cause was, that both the `TerminalDevice` and the `SerialDevice` were structs.
When they called their super constructor, the relevant parts of the `TerminalDevice` haven't been set.
For the serial device this didn't matter, because it doesn't keep any state.
The TerminalDevice was actually fully functional as a Device, but since the foreground and background colors were initialized to 0x0 (Black), you couldn't see anything.

I will push a fix within the next few minutes.
